apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
#    image: gcr.io/kaniko-project/executor:latest
    image: registry.aliyuncs.com/kaniko-project/executor:latest
    args:
    - "--dockerfile=/python-docker/Dockerfile"
    - "--context=gs:/python-docker/"
    - "--destination=ghost.harbor.com/library/python-docker:v1.0>"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /secret
    - name: python-docker
      mountPath: /python-docker
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/kaniko-secret.json
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: kaniko-secret
  - name: python-docker
    hostPath: 
      path: /root/python-docker
